config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :crags do
    resources :sectors do
      resources :routes
    end
  end
  resources :sectors, only: [:show]
  resources :routes, only: [:create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crag.rb
class Crag < ApplicationRecord
  has_many :sectors
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :sector

  validates_presence_of :name, :grade
  
end

app/models/sector.rb
class Sector < ApplicationRecord
  belongs_to :crag
  has_many :routes
  mount_uploader :image, ImageUploader

  def update_routes_numbers
    # sort routes by its start x coordinate to update position on sector
    rts = routes.sort_by { |route| JSON.parse(route.coords)[0]['x'] }
    rts.each.with_index(1) { |route, index| route.update_attribute(:number, index) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/crags_controller.rb
class CragsController < ApplicationController

  def index
    @crags = Crag.all
    @crag = Crag.new
  end

  def create
    crag = Crag.create(crag_params)
    render js: "window.location = '#{crag_path(crag)}'"
  end

  def show
    @crag = Crag.find(params[:id])
    @sector = Sector.new
  end

  private

  def crag_params
    params.require(:crag).permit(:name, :marker)
  end

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:edit, :update, :destroy]


  def create
    @route = Route.create(route_params)
    @sector = @route.sector
    respond_to do |format|
      format.html { redirect_to sector_path(@sector) }
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    @route.update(route_params)
    @route.sector.update_routes_numbers
    render js: "window.location = '#{sector_path(@route.sector)}'"
  end

  def destroy
    @sector = @route.sector
    if @route.destroy
      respond_to do |format|
        format.html { redirect_to @sector }
      end
    end
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, :grade, :coords, :sector_id)
  end

end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: [:show, :edit, :update]

  def create
    sector = Sector.create(sector_params)
    crag = Crag.find(params[:crag_id])
    redirect_to crag_sector_path(crag, sector)
  end

  def show
    
  end

  def edit
    @crag = Crag.find(params[:crag_id])
  end

  def update
    @sector.update(sector_params)
    redirect_to crag_sector_path(@sector)
  end

  private

  def sector_params
    params.require(:sector).permit(:name, :crag_id, :image)
  end

  def set_sector
    @sector = Sector.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crags_helper.rb
module CragsHelper
end

app/views/crags/_form.html.erb
<%= form_with model: @crag, id: 'form', local: true do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/crags/index.html.erb
<h1>Crags</h1>
  <ul>
    <% @crags.each do |crag| %>
      <li><%= link_to "#{crag.name}", crag_path(crag) %>
          (sectors: <%= crag.sectors.size %>)</li>
    <% end %>
  </ul>

app/views/crags/new.html.erb
<h2>Add new crag</h2>
<div id="map"></div>
<div style="display: none;">
<div id="form">
     <table>
     <tr><td>Name:</td> <td><input type='text' id='name'/> </td> </tr>
     <tr>
       <td>Type:</td> <td><select id='type'> +
                <option value='sport' SELECTED>sport</option>
                <option value='boulder'>boulder</option>
                </select> </td></tr>
                <tr><td></td>
                <td><input type='button' value='Save', onclick='saveCrag()'/></td></tr>
     </table>
   </div>
   <div id="message">Location saved</div>
</div>

<script src="/assets/javascripts/map.js"></script>
<script async defer
   src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA2hKZ1elA8sZnU67r3kG1uqukhNBtpeHM&callback=initMap">
   </script>

app/views/crags/show.html.erb
<h1><%= @crag.name %></h1>
<div id="map", data-marker="<%= @crag.marker %>"></div>
<h2>Sectors</h2>
<ul>
  <% @crag.sectors.each do |sector| %>
    <li><%= link_to "#{sector.name}", crag_sector_path(@crag, sector) %>
        (routes: <%= sector.routes.size %>)</li>
  <% end %>
</ul>


<h2>Add sector</h2>
<%= render 'sectors/form' %>

<%= link_to 'Crags', crags_path %>
<script>
function initMap() {
var mark = $('#map').data('marker');
  var point = {lat: mark.lat, lng: mark.lng};
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 4,
    center: point
  });
  var marker = new google.maps.Marker({
    position: point,
    map: map
  });
}
   </script>
   <script async defer
   src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA2hKZ1elA8sZnU67r3kG1uqukhNBtpeHM&callback=initMap">
   </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClimbingTopo</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <%= link_to 'Crags', crags_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

   <main role="main" class="container">
    <%= yield %>
   </main><!-- /.container -->

   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

app/views/routes/_form.html.erb
<%= form_for Route.new, url: { controller: 'routes', action: 'create' }, remote: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :grade %>
    <%= f.text_field :grade %>
  </div>
  <%= f.hidden_field :sector_id, value: @sector.id %>
  <%= f.submit 'Add', class: "btn btn-primary", id: 'add_route' %>
<% end %>

app/views/routes/_route.html.erb
<div id="<%= route.number %>" class="list-group-item">
  <%= route.number %>.
  <%= route.name %>,
  <%= route.grade %>


  <div id="draw_route">
    <%= button_to 'Draw', edit_route_path(route), method: :get, id: "draw_route",
          class: 'btn btn-link',
          'data-toggle': 'modal', 'data-target': "#myModal", remote: true %>
  </div>
  <%= link_to 'Delete', route_path(route), method: :delete %>
</div>

app/views/routes/_route_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Draw Route</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="canvas_container2">
          <canvas id="sector2"
                  width="<%= @sector.image.width %>"
                  height="<%= @sector.image.height %>"
                  style="border: solid 1px #000"
                  data-img="<%= @sector.image_url.to_s %>"
                  data-routes="<%= @sector.routes.to_json %>"
          </canvas>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" id="close" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" id="undo" class="btn btn-secondary">Undo</button>
      </div>
    </div>
  </div>
</div>

app/views/routes/create.js.erb
$('.list-group').html("<%=j render partial: 'routes/route', collection: @sector.routes %>");

app/views/routes/edit.js.erb
if($('#save').length === 0) {
  $('<button/>', {
    text: 'save',
    id: 'save',
    class: 'btn btn-primary',
    'data-ajax': "<%= route_path(params[:id]) %>",
    'data-dismiss': 'modal'
  }).appendTo('.modal-footer');
  $("#save").click(saveRoute);
}

app/views/sectors/_form.html.erb
<%= form_with model: [@crag, @sector], local: true, html: {multipart: true} do |form| %>
  <p><%= form.text_field :name %></p>
  <%= form.hidden_field :crag_id, value: params[:id] %>
  <p><%= form.file_field :image %></p>
  <p><%= form.submit %></p>
<% end %>

app/views/sectors/edit.html.erb
<h1>Edit <%= @sector.name %></h1>
<%= render 'form' %>

<div id="canvas_container" data-img="<%= @sector.image_url.to_s %>"></div>

<button id='save' data-ajax="<%= crag_sector_routes_path(@crag, @sector) %>"
  data-sector-id="<%= @sector.id %>">Save</button>
<script src="http://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.19/fabric.min.js"></script>
<script src="/assets/javascripts/drawRoute.js"></script>

app/views/sectors/show.html.erb
<h2>Crag: <%= link_to "#{@sector.crag.name}", crag_path(@sector.crag) %></h2>

<div class="row">
  <div class="col">
    <h1 id="sector_name"><%= @sector.name %> </h1>
    <%= link_to "Edit", edit_crag_sector_path(@sector.crag.id, @sector) %>
    <br />

      <div id="canvas_container">
        <canvas id="sector"
                width="<%= @sector.image.width %>"
                height="<%= @sector.image.height %>"
                style="border: solid 1px #000"
                data-img="<%= @sector.image_url.to_s %>"
                data-routes="<%= @sector.routes.to_json %>"
        </canvas>
      </div>
    </div>
  <div class="col">
    <div id="route_form">
      <h2>Add Route</h2>
      <%= render 'routes/form' %>
    </div>

    <div id="sector_routes" style="clear: both;">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Routes</h3>
        </div>
        <ul class="list-group">
          <%= render partial: 'routes/route', collection: @sector.routes %>
        </ul>
      </div>

    </div>
  </div>
<!-- Modal -->
<div id="route_modal">
  <%= render 'routes/route_modal' %>
</div>

<script src="http://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.19/fabric.min.js"></script>
<script src="/assets/javascripts/canvas.js"></script>